# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения'),
        ),
    ]
