# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-28 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=1234567890, max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
